language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
git:
  depth: 3
script:
  - yarn build
  - echo 'carlosarboleda.co' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB
  local-dir: out/
  target-branch: master
  commit_message: 'Deploy release ${TRAVIS_TAG}'
  on:
    branch: develop